version: '3.8'
services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto-no-tls.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  http-server:
    image: python:3.11-slim
    container_name: http-server
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install flask && python -u http_server.py"
    ports:
      - "5000:5000"
    restart: unless-stopped

  coap-server:
    build:
      context: .
      dockerfile: Dockerfile.coap
    container_name: coap-server
    ports:
      - "5683:5683/udp"
    restart: unless-stopped

volumes:
  mosq_data:
  mosq_log:
